#This workflow will install Python dependencies, lint using Black, run tests using Pytest
#and Deploy the FastAPI app to Heroku
name: fastapi-github-actions-test

on:
  #Trigger the workflow on a push event to the master branch only
  push:
    branches: [main]

#A workflow job running sequentially
jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest
    #steps: defines a series of tasks executed by the Job
    steps:
      - uses: actions/checkout@v2

      #Task for setting up Python 3.11.4 using actions/setup-python@v2 Github action
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      #Task for installing dependencies, multi-line command
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Server
        run: gunicorn --chdir src -w 1 -k uvicorn.workers.UvicornWorker app:app
